const countries = {
  'Argentina': 'ar',
  'The Bahamas': 'bs',
  'Barbados': 'bb',
  'Belize': 'bz',
  'Brazil': 'br',
  'Bolivia': 'bp',
  'Canada': 'ca',
  'Chile': 'cl',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Guyana': 'gy',
  'Jamaica': 'jm',
  'Mexico': 'mx',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Trinidad and Tobago': 'tt',
  'Uruguay': 'uy',

  'Albania': 'al',
  'Armenia': 'am',
  'Azerbaijan': 'az',
  'Belgium': 'be',
  'Bosnia and Herzegovina': 'ba',
  'Croatia': 'hr',
  'Cyprus': 'cy',
  'France': 'fr',
  'Greece': 'gr',
  'Italy': 'it',
  'Ireland': 'ie',
  'Kosovo': 'kv',
  'North Macedonia': 'mk',
  'The Netherlands': 'nl',
  'Portugal': 'pt',
  'Serbia': 'rs',
  'Spain and Andorra': 'es',
  'Turkiye': 'tr',
  'United Kingdom': 'gb',

  'Israel, Jerusalem, The West Bank, and Gaza': 'il',
  'United Arab Emirates': 'ae',
  'Iran': 'ir',

  'Angola': 'ao',
  'Cameroon': 'cm',
  'Cabo Verde': 'cv',
  'The Democratic Republic of the Congo': 'cd',
  'Ethiopia': 'et',
  'Kenya': 'ke',
  'Rwanda': 'rw',
  'Senegal': 'sn',
  'Tanzania': 'tz',
  'South Africa': 'za',
  'Uganda': 'ug',
  'Zambia': 'zm',
};

module.exports = countries
